<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1 align=center><font size = 5>Assignment: SQL Notebook for Peer Assignment</font></h1>

Estimated time needed: **60** minutes.

## Introduction
Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones. 

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage. 


Therefore if we can determine if the first stage will land, we can determine the cost of a launch. 

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

 <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv" target="_blank">Spacex DataSet</a>

In [4]:
!pip install sqlalchemy==1.3.9

Collecting sqlalchemy==1.3.9
  Downloading SQLAlchemy-1.3.9.tar.gz (6.0 MB)
     ---------------------------------------- 0.0/6.0 MB ? eta -:--:--
     - -------------------------------------- 0.3/6.0 MB ? eta -:--:--
     ----- ---------------------------------- 0.8/6.0 MB 2.6 MB/s eta 0:00:03
     ---------- ----------------------------- 1.6/6.0 MB 2.9 MB/s eta 0:00:02
     -------------- ------------------------- 2.1/6.0 MB 3.0 MB/s eta 0:00:02
     --------------------- ------------------ 3.1/6.0 MB 3.4 MB/s eta 0:00:01
     ----------------------------- ---------- 4.5/6.0 MB 3.9 MB/s eta 0:00:01
     -------------------------------------- - 5.8/6.0 MB 4.4 MB/s eta 0:00:01
     ---------------------------------------- 6.0/6.0 MB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py): started
  Building wheel for sqlalchemy (setup.py): finished with status 'done'
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.3.9-cp312-cp312-win_amd64.whl size=1164452 sha256=ea0b395348562842f216567e00aeee1f48f30f87a4c751c0a4c6c2bc217ae21e
  Stored in directory: c:\users\chris\appdata\local\pip\cache\wheels\b3\1c\42\0e26b8d512adc6bce10ff71a05229366b4ccec641cd3b42111
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.40
    Uninstalling SQLAlchemy-2.0.40:
      Successfully uninstalled SQLAlchemy-2.0.40
Successfully installed sqlalchemy-1.3.9

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.3.9 which is incompatible.

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [6]:
!pip install ipython-sql
!pip install ipython-sql prettytable

Requirement already satisfied: ipython-sql in c:\users\chris\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: prettytable in c:\users\chris\anaconda3\lib\site-packages (from ipython-sql) (3.16.0)
Requirement already satisfied: ipython in c:\users\chris\anaconda3\lib\site-packages (from ipython-sql) (8.27.0)
Collecting sqlalchemy>=2.0 (from ipython-sql)
  Using cached sqlalchemy-2.0.40-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: sqlparse in c:\users\chris\anaconda3\lib\site-packages (from ipython-sql) (0.5.3)
Requirement already satisfied: six in c:\users\chris\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in c:\users\chris\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet>=1 in c:\users\chris\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\chris\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.11.0)
Requirement already satisfied: decorator in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.15.1)
Requirement already satisfied: stack-data in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: colorama in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: wcwidth in c:\users\chris\anaconda3\lib\site-packages (from prettytable->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\chris\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: executing in c:\users\chris\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in c:\users\chris\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\chris\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)
Using cached sqlalchemy-2.0.40-cp312-cp312-win_amd64.whl (2.1 MB)
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.3.9
    Uninstalling SQLAlchemy-1.3.9:
      Successfully uninstalled SQLAlchemy-1.3.9
Successfully installed sqlalchemy-2.0.40
Requirement already satisfied: ipython-sql in c:\users\chris\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: prettytable in c:\users\chris\anaconda3\lib\site-packages (3.16.0)
Requirement already satisfied: ipython in c:\users\chris\anaconda3\lib\site-packages (from ipython-sql) (8.27.0)
Requirement already satisfied: sqlalchemy>=2.0 in c:\users\chris\anaconda3\lib\site-packages (from ipython-sql) (2.0.40)
Requirement already satisfied: sqlparse in c:\users\chris\anaconda3\lib\site-packages (from ipython-sql) (0.5.3)
Requirement already satisfied: six in c:\users\chris\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in c:\users\chris\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth in c:\users\chris\anaconda3\lib\site-packages (from prettytable) (0.2.5)
Requirement already satisfied: greenlet>=1 in c:\users\chris\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\chris\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.11.0)
Requirement already satisfied: decorator in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.15.1)
Requirement already satisfied: stack-data in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: colorama in c:\users\chris\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\chris\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: executing in c:\users\chris\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in c:\users\chris\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\chris\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)

In [7]:
%load_ext sql

In [8]:
import csv, sqlite3
import prettytable
prettytable.DEFAULT = 'DEFAULT'

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

In [9]:
!pip install -q pandas

In [10]:
%sql sqlite:///my_data1.db

In [17]:
import pandas as pd
df = pd.read_csv("dataset_part_2.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

90

**Note:This below code is added to remove blank rows from table**

In [20]:
#DROP THE TABLE IF EXISTS

%sql DROP TABLE IF EXISTS SPACEXTABLE;

 * sqlite:///my_data1.db
Done.

[]

In [22]:
%sql create table SPACEXTABLE as select * from SPACEXTBL where Date is not null

 * sqlite:///my_data1.db
Done.

[]

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

**Note: If the column names are in mixed case enclose it in double quotes
   For Example "Landing_Outcome"**

### Task 1




##### Display the names of the unique launch sites  in the space mission

In [27]:
%sql select * from SPACEXTABLE

 * sqlite:///my_data1.db
Done.

[(1, '2010-06-04', 'Falcon 9', 6123.547647058824, 'LEO', 'CCSFS SLC 40', 'None None', 1, 0, 0, 0, None, 1.0, 0, 'B0003', -80.577366, 28.5618571, 0),
 (2, '2012-05-22', 'Falcon 9', 525.0, 'LEO', 'CCSFS SLC 40', 'None None', 1, 0, 0, 0, None, 1.0, 0, 'B0005', -80.577366, 28.5618571, 0),
 (3, '2013-03-01', 'Falcon 9', 677.0, 'ISS', 'CCSFS SLC 40', 'None None', 1, 0, 0, 0, None, 1.0, 0, 'B0007', -80.577366, 28.5618571, 0),
 (4, '2013-09-29', 'Falcon 9', 500.0, 'PO', 'VAFB SLC 4E', 'False Ocean', 1, 0, 0, 0, None, 1.0, 0, 'B1003', -120.610829, 34.632093, 0),
 (5, '2013-12-03', 'Falcon 9', 3170.0, 'GTO', 'CCSFS SLC 40', 'None None', 1, 0, 0, 0, None, 1.0, 0, 'B1004', -80.577366, 28.5618571, 0),
 (6, '2014-01-06', 'Falcon 9', 3325.0, 'GTO', 'CCSFS SLC 40', 'None None', 1, 0, 0, 0, None, 1.0, 0, 'B1005', -80.577366, 28.5618571, 0),
 (7, '2014-04-18', 'Falcon 9', 2296.0, 'ISS', 'CCSFS SLC 40', 'True Ocean', 1, 0, 0, 1, None, 1.0, 0, 'B1006', -80.577366, 28.5618571, 1),
 (8, '2014-07-14', 'Falcon 9', 1316.0, 'LEO', 'CCSFS SLC 40', 'True Ocean', 1, 0, 0, 1, None, 1.0, 0, 'B1007', -80.577366, 28.5618571, 1),
 (9, '2014-08-05', 'Falcon 9', 4535.0, 'GTO', 'CCSFS SLC 40', 'None None', 1, 0, 0, 0, None, 1.0, 0, 'B1008', -80.577366, 28.5618571, 0),
 (10, '2014-09-07', 'Falcon 9', 4428.0, 'GTO', 'CCSFS SLC 40', 'None None', 1, 0, 0, 0, None, 1.0, 0, 'B1011', -80.577366, 28.5618571, 0),
 (11, '2014-09-21', 'Falcon 9', 2216.0, 'ISS', 'CCSFS SLC 40', 'False Ocean', 1, 0, 0, 0, None, 1.0, 0, 'B1010', -80.577366, 28.5618571, 0),
 (12, '2015-01-10', 'Falcon 9', 2395.0, 'ISS', 'CCSFS SLC 40', 'False ASDS', 1, 1, 0, 1, '5e9e3032383ecb761634e7cb', 1.0, 0, 'B1012', -80.577366, 28.5618571, 0),
 (13, '2015-02-11', 'Falcon 9', 570.0, 'ES-L1', 'CCSFS SLC 40', 'True Ocean', 1, 1, 0, 1, None, 1.0, 0, 'B1013', -80.577366, 28.5618571, 1),
 (14, '2015-04-14', 'Falcon 9', 1898.0, 'ISS', 'CCSFS SLC 40', 'False ASDS', 1, 1, 0, 1, '5e9e3032383ecb761634e7cb', 1.0, 0, 'B1015', -80.577366, 28.5618571, 0),
 (15, '2015-04-27', 'Falcon 9', 4707.0, 'GTO', 'CCSFS SLC 40', 'None None', 1, 0, 0, 0, None, 1.0, 0, 'B1016', -80.577366, 28.5618571, 0),
 (16, '2015-06-28', 'Falcon 9', 2477.0, 'ISS', 'CCSFS SLC 40', 'None ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 1.0, 0, 'B1018', -80.577366, 28.5618571, 0),
 (17, '2015-12-22', 'Falcon 9', 2034.0, 'LEO', 'CCSFS SLC 40', 'True RTLS', 1, 1, 0, 1, '5e9e3032383ecb267a34e7c7', 1.0, 0, 'B1019', -80.577366, 28.5618571, 1),
 (18, '2016-01-17', 'Falcon 9', 553.0, 'PO', 'VAFB SLC 4E', 'False ASDS', 1, 1, 0, 1, '5e9e3033383ecbb9e534e7cc', 1.0, 0, 'B1017', -120.610829, 34.632093, 0),
 (19, '2016-03-04', 'Falcon 9', 5271.0, 'GTO', 'CCSFS SLC 40', 'False ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 1.0, 0, 'B1020', -80.577366, 28.5618571, 0),
 (20, '2016-04-08', 'Falcon 9', 3136.0, 'ISS', 'CCSFS SLC 40', 'True ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 2.0, 1, 'B1021', -80.577366, 28.5618571, 1),
 (21, '2016-05-06', 'Falcon 9', 4696.0, 'GTO', 'CCSFS SLC 40', 'True ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 2.0, 0, 'B1022', -80.577366, 28.5618571, 1),
 (22, '2016-05-27', 'Falcon 9', 3100.0, 'GTO', 'CCSFS SLC 40', 'True ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 2.0, 1, 'B1023', -80.577366, 28.5618571, 1),
 (23, '2016-07-18', 'Falcon 9', 2257.0, 'ISS', 'CCSFS SLC 40', 'True RTLS', 1, 1, 0, 1, '5e9e3032383ecb267a34e7c7', 2.0, 1, 'B1025', -80.577366, 28.5618571, 1),
 (24, '2016-08-14', 'Falcon 9', 4600.0, 'GTO', 'CCSFS SLC 40', 'True ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 2.0, 0, 'B1026', -80.577366, 28.5618571, 1),
 (25, '2016-09-01', 'Falcon 9', 5500.0, 'GTO', 'CCSFS SLC 40', 'None ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 3.0, 0, 'B1028', -80.577366, 28.5618571, 0),
 (26, '2017-01-14', 'Falcon 9', 9600.0, 'PO', 'VAFB SLC 4E', 'True ASDS', 1, 1, 0, 1, '5e9e3033383ecbb9e534e7cc', 3.0, 1, 'B1029', -120.610829, 34.632093, 1),
 (27, '2017-02-19', 'Falcon 9', 2490.0, 'ISS', 'KSC LC 39A', 'True RTLS', 1, 1, 0, 1, '5e9e3032383ecb267a34e7c7', 3.0, 1, 'B1031', -80.6039558, 28.6080585, 1),
 (28, '2017-03-16', 'Falcon 9', 5600.0, 'GTO', 'KSC LC 39A', 'None None', 1, 0, 0, 0, None, 3.0, 0, 'B1030', -80.6039558, 28.6080585, 0),
 (29, '2017-03-30', 'Falcon 9', 5300.0, 'GTO', 'KSC LC 39A', 'True ASDS', 2, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 2.0, 1, 'B1021', -80.6039558, 28.6080585, 1),
 (30, '2017-05-01', 'Falcon 9', 6123.547647058824, 'LEO', 'KSC LC 39A', 'True RTLS', 1, 1, 0, 1, '5e9e3032383ecb267a34e7c7', 3.0, 1, 'B1032', -80.6039558, 28.6080585, 1),
 (31, '2017-05-15', 'Falcon 9', 6070.0, 'GTO', 'KSC LC 39A', 'None None', 1, 0, 0, 0, None, 3.0, 0, 'B1034', -80.6039558, 28.6080585, 0),
 (32, '2017-06-03', 'Falcon 9', 2708.0, 'ISS', 'KSC LC 39A', 'True RTLS', 1, 1, 0, 1, '5e9e3032383ecb267a34e7c7', 3.0, 1, 'B1035', -80.6039558, 28.6080585, 1),
 (33, '2017-06-23', 'Falcon 9', 3669.0, 'GTO', 'KSC LC 39A', 'True ASDS', 2, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 3.0, 1, 'B1029', -80.6039558, 28.6080585, 1),
 (34, '2017-06-25', 'Falcon 9', 9600.0, 'PO', 'VAFB SLC 4E', 'True ASDS', 1, 1, 0, 1, '5e9e3033383ecbb9e534e7cc', 3.0, 1, 'B1036', -120.610829, 34.632093, 1),
 (35, '2017-07-05', 'Falcon 9', 6761.0, 'GTO', 'KSC LC 39A', 'None None', 1, 0, 0, 0, None, 3.0, 0, 'B1037', -80.6039558, 28.6080585, 0),
 (36, '2017-08-14', 'Falcon 9', 2910.0, 'ISS', 'KSC LC 39A', 'True RTLS', 1, 1, 0, 1, '5e9e3032383ecb267a34e7c7', 4.0, 1, 'B1039', -80.6039558, 28.6080585, 1),
 (37, '2017-08-24', 'Falcon 9', 475.0, 'SSO', 'VAFB SLC 4E', 'True ASDS', 1, 1, 0, 1, '5e9e3033383ecbb9e534e7cc', 3.0, 1, 'B1038', -120.610829, 34.632093, 1),
 (38, '2017-09-07', 'Falcon 9', 4990.0, 'LEO', 'KSC LC 39A', 'True RTLS', 1, 1, 0, 1, '5e9e3032383ecb267a34e7c7', 4.0, 1, 'B1040', -80.6039558, 28.6080585, 1),
 (39, '2017-10-09', 'Falcon 9', 9600.0, 'PO', 'VAFB SLC 4E', 'True ASDS', 1, 1, 0, 1, '5e9e3033383ecbb9e534e7cc', 4.0, 1, 'B1041', -120.610829, 34.632093, 1),
 (40, '2017-10-11', 'Falcon 9', 5200.0, 'GTO', 'KSC LC 39A', 'True ASDS', 2, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 3.0, 1, 'B1031', -80.6039558, 28.6080585, 1),
 (41, '2017-10-30', 'Falcon 9', 3700.0, 'GTO', 'KSC LC 39A', 'True ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 4.0, 0, 'B1042', -80.6039558, 28.6080585, 1),
 (42, '2017-12-15', 'Falcon 9', 2205.0, 'ISS', 'CCSFS SLC 40', 'True RTLS', 2, 1, 1, 1, '5e9e3032383ecb267a34e7c7', 3.0, 1, 'B1035', -80.577366, 28.5618571, 1),
 (43, '2017-12-23', 'Falcon 9', 9600.0, 'PO', 'VAFB SLC 4E', 'True Ocean', 2, 1, 1, 0, None, 3.0, 1, 'B1036', -120.610829, 34.632093, 1),
 (44, '2018-01-08', 'Falcon 9', 6123.547647058824, 'LEO', 'CCSFS SLC 40', 'True RTLS', 1, 1, 0, 1, '5e9e3032383ecb267a34e7c7', 4.0, 1, 'B1043', -80.577366, 28.5618571, 1),
 (45, '2018-01-31', 'Falcon 9', 4230.0, 'GTO', 'CCSFS SLC 40', 'True Ocean', 2, 1, 1, 1, None, 3.0, 1, 'B1032', -80.577366, 28.5618571, 1),
 (46, '2018-03-06', 'Falcon 9', 6092.0, 'GTO', 'CCSFS SLC 40', 'None None', 1, 1, 0, 1, None, 4.0, 0, 'B1044', -80.577366, 28.5618571, 0),
 (47, '2018-03-30', 'Falcon 9', 9600.0, 'PO', 'VAFB SLC 4E', 'None None', 2, 1, 1, 1, None, 4.0, 1, 'B1041', -120.610829, 34.632093, 0),
 (48, '2018-04-02', 'Falcon 9', 2760.0, 'ISS', 'CCSFS SLC 40', 'None None', 2, 1, 1, 1, None, 4.0, 1, 'B1039', -80.577366, 28.5618571, 0),
 (49, '2018-04-18', 'Falcon 9', 350.0, 'HEO', 'CCSFS SLC 40', 'True ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 4.0, 1, 'B1045', -80.577366, 28.5618571, 1),
 (50, '2018-05-11', 'Falcon 9', 3750.0, 'GTO', 'KSC LC 39A', 'True ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 3, 'B1046', -80.6039558, 28.6080585, 1),
 (51, '2018-06-04', 'Falcon 9', 5383.85, 'GTO', 'CCSFS SLC 40', 'None None', 2, 0, 1, 0, None, 4.0, 1, 'B1040', -80.577366, 28.5618571, 0),
 (52, '2018-06-29', 'Falcon 9', 2410.0, 'ISS', 'CCSFS SLC 40', 'None None', 2, 0, 1, 0, None, 4.0, 1, 'B1045', -80.577366, 28.5618571, 0),
 (53, '2018-07-22', 'Falcon 9', 7076.0, 'GTO', 'CCSFS SLC 40', 'True ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 2, 'B1047', -80.577366, 28.5618571, 1),
 (54, '2018-07-25', 'Falcon 9', 9600.0, 'PO', 'VAFB SLC 4E', 'True ASDS', 1, 1, 0, 1, '5e9e3033383ecbb9e534e7cc', 5.0, 4, 'B1048', -120.610829, 34.632093, 1),
 (55, '2018-08-07', 'Falcon 9', 5800.0, 'GTO', 'CCSFS SLC 40', 'True ASDS', 2, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 3, 'B1046', -80.577366, 28.5618571, 1),
 (56, '2018-09-10', 'Falcon 9', 7060.0, 'GTO', 'CCSFS SLC 40', 'True ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 9, 'B1049', -80.577366, 28.5618571, 1),
 (57, '2018-10-08', 'Falcon 9', 2800.0, 'SSO', 'VAFB SLC 4E', 'True RTLS', 2, 1, 1, 1, '5e9e3032383ecb554034e7c9', 5.0, 4, 'B1048', -120.610829, 34.632093, 1),
 (58, '2018-11-15', 'Falcon 9', 3000.0, 'GTO', 'KSC LC 39A', 'True ASDS', 2, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 2, 'B1047', -80.6039558, 28.6080585, 1),
 (59, '2018-12-03', 'Falcon 9', 4000.0, 'SSO', 'VAFB SLC 4E', 'True ASDS', 3, 1, 1, 1, '5e9e3033383ecbb9e534e7cc', 5.0, 3, 'B1046', -120.610829, 34.632093, 1),
 (60, '2018-12-05', 'Falcon 9', 2573.0, 'ISS', 'CCSFS SLC 40', 'False RTLS', 1, 1, 0, 1, '5e9e3032383ecb267a34e7c7', 5.0, 0, 'B1050', -80.577366, 28.5618571, 0),
 (61, '2018-12-23', 'Falcon 9', 4400.0, 'MEO', 'CCSFS SLC 40', 'None None', 1, 0, 0, 0, None, 5.0, 0, 'B1054', -80.577366, 28.5618571, 0),
 (62, '2019-01-11', 'Falcon 9', 9600.0, 'PO', 'VAFB SLC 4E', 'True ASDS', 2, 1, 1, 1, '5e9e3033383ecbb9e534e7cc', 5.0, 9, 'B1049', -120.610829, 34.632093, 1),
 (63, '2019-03-02', 'Falcon 9', 12259.0, 'ISS', 'KSC LC 39A', 'True ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 12, 'B1051', -80.6039558, 28.6080585, 1),
 (64, '2019-05-04', 'Falcon 9', 2482.0, 'ISS', 'CCSFS SLC 40', 'True ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 3, 'B1056', -80.577366, 28.5618571, 1),
 (65, '2019-05-24', 'Falcon 9', 13200.0, 'VLEO', 'CCSFS SLC 40', 'True ASDS', 3, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 9, 'B1049', -80.577366, 28.5618571, 1),
 (66, '2019-06-12', 'Falcon 9', 1425.0, 'SSO', 'VAFB SLC 4E', 'True RTLS', 2, 1, 1, 1, '5e9e3032383ecb554034e7c9', 5.0, 12, 'B1051', -120.610829, 34.632093, 1),
 (67, '2019-07-25', 'Falcon 9', 2227.7, 'ISS', 'CCSFS SLC 40', 'True RTLS', 2, 1, 1, 1, '5e9e3032383ecb267a34e7c7', 5.0, 3, 'B1056', -80.577366, 28.5618571, 1),
 (68, '2019-08-06', 'Falcon 9', 6500.0, 'GTO', 'CCSFS SLC 40', 'None None', 3, 0, 1, 0, None, 5.0, 2, 'B1047', -80.577366, 28.5618571, 0),
 (69, '2019-11-11', 'Falcon 9', 15600.0, 'VLEO', 'CCSFS SLC 40', 'True ASDS', 4, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 4, 'B1048', -80.577366, 28.5618571, 1),
 (70, '2019-12-05', 'Falcon 9', 5000.0, 'ISS', 'CCSFS SLC 40', 'True ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 5, 'B1059', -80.577366, 28.5618571, 1),
 (71, '2019-12-17', 'Falcon 9', 6800.0, 'GTO', 'CCSFS SLC 40', 'True ASDS', 3, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 3, 'B1056', -80.577366, 28.5618571, 1),
 (72, '2020-01-07', 'Falcon 9', 15600.0, 'VLEO', 'CCSFS SLC 40', 'True ASDS', 4, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 9, 'B1049', -80.577366, 28.5618571, 1),
 (73, '2020-01-19', 'Falcon 9', 6123.547647058824, 'SO', 'KSC LC 39A', 'None None', 4, 0, 1, 0, None, 5.0, 3, 'B1046', -80.6039558, 28.6080585, 0),
 (74, '2020-01-29', 'Falcon 9', 15600.0, 'VLEO', 'CCSFS SLC 40', 'True ASDS', 3, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 12, 'B1051', -80.577366, 28.5618571, 1),
 (75, '2020-02-17', 'Falcon 9', 15600.0, 'VLEO', 'CCSFS SLC 40', 'False ASDS', 4, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 3, 'B1056', -80.577366, 28.5618571, 0),
 (76, '2020-03-07', 'Falcon 9', 1977.0, 'ISS', 'CCSFS SLC 40', 'True RTLS', 2, 1, 1, 1, '5e9e3032383ecb267a34e7c7', 5.0, 5, 'B1059', -80.577366, 28.5618571, 1),
 (77, '2020-03-18', 'Falcon 9', 15600.0, 'VLEO', 'KSC LC 39A', 'False ASDS', 5, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 4, 'B1048', -80.6039558, 28.6080585, 0),
 (78, '2020-04-22', 'Falcon 9', 15600.0, 'VLEO', 'KSC LC 39A', 'True ASDS', 4, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 12, 'B1051', -80.6039558, 28.6080585, 1),
 (79, '2020-05-30', 'Falcon 9', 9525.0, 'ISS', 'KSC LC 39A', 'True ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 13, 'B1058', -80.6039558, 28.6080585, 1),
 (80, '2020-06-04', 'Falcon 9', 15600.0, 'VLEO', 'CCSFS SLC 40', 'True ASDS', 5, 1, 1, 1, '5e9e3033383ecbb9e534e7cc', 5.0, 9, 'B1049', -80.577366, 28.5618571, 1),
 (81, '2020-06-13', 'Falcon 9', 15600.0, 'VLEO', 'CCSFS SLC 40', 'True ASDS', 3, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 5, 'B1059', -80.577366, 28.5618571, 1),
 (82, '2020-06-30', 'Falcon 9', 3880.0, 'MEO', 'CCSFS SLC 40', 'True ASDS', 1, 1, 0, 1, '5e9e3033383ecbb9e534e7cc', 5.0, 12, 'B1060', -80.577366, 28.5618571, 1),
 (83, '2020-07-20', 'Falcon 9', 6123.547647058824, 'GEO', 'CCSFS SLC 40', 'True ASDS', 2, 1, 1, 1, '5e9e3033383ecbb9e534e7cc', 5.0, 13, 'B1058', -80.577366, 28.5618571, 1),
 (84, '2020-08-18', 'Falcon 9', 15600.0, 'VLEO', 'CCSFS SLC 40', 'True ASDS', 6, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 9, 'B1049', -80.577366, 28.5618571, 1),
 (85, '2020-08-30', 'Falcon 9', 1600.0, 'SSO', 'CCSFS SLC 40', 'True RTLS', 4, 1, 1, 1, '5e9e3032383ecb267a34e7c7', 5.0, 5, 'B1059', -80.577366, 28.5618571, 1),
 (86, '2020-09-03', 'Falcon 9', 15600.0, 'VLEO', 'KSC LC 39A', 'True ASDS', 2, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 12, 'B1060', -80.6039558, 28.6080585, 1),
 (87, '2020-10-06', 'Falcon 9', 15600.0, 'VLEO', 'KSC LC 39A', 'True ASDS', 3, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 13, 'B1058', -80.6039558, 28.6080585, 1),
 (88, '2020-10-18', 'Falcon 9', 15600.0, 'VLEO', 'KSC LC 39A', 'True ASDS', 6, 1, 1, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 12, 'B1051', -80.6039558, 28.6080585, 1),
 (89, '2020-10-24', 'Falcon 9', 15600.0, 'VLEO', 'CCSFS SLC 40', 'True ASDS', 3, 1, 1, 1, '5e9e3033383ecbb9e534e7cc', 5.0, 12, 'B1060', -80.577366, 28.5618571, 1),
 (90, '2020-11-05', 'Falcon 9', 3681.0, 'MEO', 'CCSFS SLC 40', 'True ASDS', 1, 1, 0, 1, '5e9e3032383ecb6bb234e7ca', 5.0, 8, 'B1062', -80.577366, 28.5618571, 1)]

In [31]:
%sql select distinct("LaunchSite") from SPACEXTABLE

 * sqlite:///my_data1.db
Done.

[('CCSFS SLC 40',), ('VAFB SLC 4E',), ('KSC LC 39A',)]


### Task 2


#####  Display 5 records where launch sites begin with the string 'CCS'

In [37]:
%sql select "LaunchSite" from SPACEXTABLE where "LaunchSite" like '%CC%' limit 5;

 * sqlite:///my_data1.db
Done.

[('CCSFS SLC 40',),
 ('CCSFS SLC 40',),
 ('CCSFS SLC 40',),
 ('CCSFS SLC 40',),
 ('CCSFS SLC 40',)]

### Task 3




##### Display the total payload mass carried by boosters launched by SPACEX

In [44]:
%sql select SUM("PayloadMass") from SPACEXTABLE;

 * sqlite:///my_data1.db
Done.

[(551119.2882352942,)]

### Task 4




##### Display average payload mass carried by booster version F9 v1.1

In [46]:
%sql select AVG("PayloadMass") from SPACEXTABLE;

 * sqlite:///my_data1.db
Done.

[(6123.547647058824,)]

### Task 5

##### List the date when the first succesful landing outcome in ground pad was acheived.


_Hint:Use min function_

In [55]:
%sql select min("Date") from SPACEXTABLE where "Outcome" like '%True RTLS%'

 * sqlite:///my_data1.db
Done.

[('2015-12-22',)]

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

In [60]:
%sql select "BoosterVersion" from SPACEXTABLE where "Outcome" like '%True ASDs%' and "PayloadMass" > 4000 and "PayloadMass" < 6000;

 * sqlite:///my_data1.db
Done.

[('Falcon 9',),
 ('Falcon 9',),
 ('Falcon 9',),
 ('Falcon 9',),
 ('Falcon 9',),
 ('Falcon 9',)]

### Task 7




##### List the total number of successful and failure mission outcomes

In [74]:
%sql select count("Outcome") as count from SPACEXTABLE where "Outcome" like '%False%' union all select count("Outcome") as count from SPACEXTABLE where "Outcome" like '%True%';

 * sqlite:///my_data1.db
Done.

[(9,), (60,)]

### Task 8



##### List all the booster_versions that have carried the maximum payload mass. Use a subquery.

### Task 9


##### List the records which will display the month names, failure landing_outcomes in drone ship ,booster versions, launch_site for the months in year 2015.

**Note: SQLLite does not support monthnames. So you need to use  substr(Date, 6,2) as month to get the months and substr(Date,0,5)='2015' for year.**

### Task 10




##### Rank the count of landing outcomes (such as Failure (drone ship) or Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order.

### Reference Links

* <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20String%20Patterns%20-%20Sorting%20-%20Grouping/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : String Patterns, Sorting and Grouping</a>  

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html?origin=www.coursera.org">Hands-on Lab: Built-in functions</a>

*  <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb">Hands-on Tutorial: Accessing Databases with SQL magic</a>

*  <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb">Hands-on Lab: Analyzing a real World Data Set</a>

## Author(s)

<h4> Lakshmi Holla </h4>

## Other Contributors

<h4> Rav Ahuja </h4>

<!--
## Change log
| Date | Version | Changed by | Change Description |
|------|--------|--------|---------|
| 2024-07-10 | 1.1 |Anita Verma | Changed Version|
| 2021-07-09 | 0.2 |Lakshmi Holla | Changes made in magic sql|
| 2021-05-20 | 0.1 |Lakshmi Holla | Created Initial Version |
-->

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>